mqtt_server_addr: "192.168.x.x"
mqtt_server_port: 1883
mqtt_username: ""
mqtt_password: ""
mqtt_client_id: "sunspec_gateway"
hass_enabled: true

units:
  - addr: "192.168.x.y:502"
    slaves: [1]

models:
  "1":
    - point: "Mn"
      interval: 300
    - point: "Md"
      interval: 300
    - point: "SN"
      interval: 300
