services:
  sunspec_gateway:
    image: sunspec_gateway:latest
    pull_policy: never
    ports:
      - "8300:8300"
    volumes:
      - "./sunspec_gateway.db:/opt/sunspec_gateway/sunspec_gateway.db"
